version: "3.3"

services:
  kafka:
    image: 'bitnami/kafka:3.2.3'
    ports:
      - 9094:9094
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,EXTERNALCLIENT://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNALCLIENT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNALCLIENT://localhost:9094
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CFG_TLS_CLIENT_AUTH=none
      - KAFKA_CLIENT_PASSWORDS=password
      - ALLOW_PLAINTEXT_LISTENER=yes

  akhq:
    image: tchiotludo/akhq:0.24.0
    volumes:
      - ./application.yml:/app/application.yml
    ports:
      - "8070:8080"
    depends_on:
      - kafka
        
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Passw0rd!1"
      - "MSSQL_PID=Express"